name: Build and Release

on:
  push:
    branches:
      - "**"
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: mingw-w64
          version: 1.0

      - name: Build
        run: make
        continue-on-error: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: version.dll
          path: out/version.dll

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: version.dll
          path: out/

      - name: Attach DLL to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "out/version.dll"
          allowUpdates: true

